# Generated by Django 3.0.5 on 2020-05-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotefiles',
            name='name',
        ),
        migrations.AddField(
            model_name='quotefiles',
            name='file_names',
            field=models.TextField(default=''),
        ),
    ]
