# Generated by Django 3.0.5 on 2020-04-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
