# Generated by Django 3.0.5 on 2020-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200524_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='file_names',
            field=models.TextField(default=''),
        ),
    ]
