# Generated by Django 3.0.5 on 2020-04-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200413_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploads',
            new_name='Upload',
        ),
    ]
