# Generated by Django 3.0.5 on 2020-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20200418_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('GENERAL', 'General')], default='ACADEMIC', max_length=8)),
                ('word_count', models.IntegerField()),
                ('name_before', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('uploaded_on', models.DateTimeField()),
                ('added_to_basket', models.BooleanField(default=False)),
                ('removed_from_basket', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchased', models.BooleanField(default=False)),
                ('submited_by', models.CharField(max_length=100)),
            ],
        ),
    ]
