# Generated by Django 3.0.5 on 2020-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_quote_file_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='file_names',
        ),
        migrations.RemoveField(
            model_name='quotefiles',
            name='file_names',
        ),
        migrations.AddField(
            model_name='quotefiles',
            name='file_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
