# Generated by Django 3.0.5 on 2020-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20200524_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('DONE', 'Done')], default='SUBMITTED', max_length=100),
        ),
    ]
