# Generated by Django 3.0.5 on 2020-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_before', models.CharField(max_length=100)),
                ('name_after', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='name_before',
        ),
        migrations.AddField(
            model_name='quote',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
