# Generated by Django 3.0.5 on 2020-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotefiles',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
