# Generated by Django 3.0.5 on 2020-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_quotefiles_quote_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='submited_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='submitted_by',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
