# Generated by Django 3.0.5 on 2020-06-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_quotefiles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotefiles',
            name='user',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('DONE', 'Done'), ('ACCEPTED', 'Accepted')], default='SUBMITTED', max_length=100),
        ),
    ]
