# Generated by Django 3.0.5 on 2020-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_auto_20200420_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='submitted_by',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
