# Generated by Django 3.0.5 on 2020-04-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_auto_20200420_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotefiles',
            old_name='name_after',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='quotefiles',
            name='name_before',
        ),
    ]
