# Generated by Django 3.0.5 on 2020-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0012_auto_20200420_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(default='ok', max_length=100),
            preserve_default=False,
        ),
    ]
