# Generated by Django 3.0.5 on 2020-06-13 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1220)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quote_ref', models.IntegerField(default=0)),
                ('file_name', models.CharField(default='', max_length=120)),
                ('superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
