# Generated by Django 3.0.5 on 2020-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200613_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
