# Generated by Django 3.0.5 on 2020-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtobasket',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
